# Generated by Django 2.0.5 on 2018-06-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20180604_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pics',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
