# Generated by Django 2.0.5 on 2018-06-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20180604_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pics',
            name='pics',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='pics',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
